# Generated by Django 5.1.1 on 2024-10-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('item_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('product_description', models.TextField()),
                ('part_number', models.CharField(max_length=20)),
                ('planned_capacity_per_day', models.BigIntegerField()),
                ('actual_capacity_until_eleven', models.BigIntegerField()),
                ('actual_capacity_until_thirteen', models.BigIntegerField()),
                ('actual_capacity_until_fiveteen', models.BigIntegerField()),
                ('actual_capacity_until_thrty_to_eighteen', models.BigIntegerField()),
                ('actual_Capacity_per_day', models.BigIntegerField()),
                ('net_production_time_per_shift', models.CharField(max_length=20)),
                ('production_takt', models.BigIntegerField()),
                ('defective_products', models.BigIntegerField()),
                ('yield_rate', models.CharField(max_length=20)),
                ('completion_ratio_per_shift', models.CharField(max_length=20)),
                ('attendance_due', models.BigIntegerField()),
                ('actual_attendence', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('login_status', models.BooleanField(default=False)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
