# Generated by Django 2.0.7 on 2018-07-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_description', models.TextField()),
                ('Part_Number', models.CharField(max_length=30)),
                ('Planned_Capacity_per_day', models.FloatField()),
                ('Actual_capacity_until_eleven', models.FloatField()),
                ('Actual_capacity_until_thirteen', models.FloatField()),
                ('Actual_capacity_until_fiveteen', models.FloatField()),
                ('Actual_capacity_until_thrty_to_eighteen', models.FloatField()),
                ('Actual_Capacity_per_day', models.FloatField()),
                ('Scheduled_downtime_per_shirft', models.FloatField()),
                ('Unscheduled_downtime_lost_per_shirft', models.FloatField()),
                ('Net_production_time_per_shift', models.FloatField()),
                ('production_takt', models.BigIntegerField()),
                ('defective_products', models.BigIntegerField()),
                ('Yield_Rate', models.CharField(max_length=20)),
                ('Completion_ratio_per_shift', models.CharField(max_length=20)),
                ('Attendance_due', models.BigIntegerField()),
                ('actual_attendence', models.BigIntegerField()),
            ],
        ),
    ]
