# Generated by Django 2.0.7 on 2018-07-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='Part_Number',
            field=models.CharField(max_length=20),
        ),
    ]
